server:
  port: 8084
spring:
  application:
    name: course-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.address}:3306/ray_course?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
