version: '3'

services:
  nacos-service:
    container_name: nacos
    image: nacos/nacos-server:1.4.1
    environment:
      MODE: standalone
    ports:
    - 8848:8848
    networks:
      - mynet
  mysql-service:
    container_name: mysql
    image: library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - /Devops/Devmysql/conf:/etc/mysql/conf.d
    - /Devops/Devmysql/data:/var/lib/mysql
    ports:
    - 3307:3306
    networks:
      - mynet
  redis-service:
    container_name: redis
    image: redis:6.0
    networks:
      - mynet
  message-service:
    container_name: message
    build:
      context: ./message-service/.
      dockerfile: Dockerfile
    networks:
      - mynet
    command:
      - "--redis.address=redis"
      - "--nacos.address=nacos"

  user-service:
    container_name: user
    build:
      context: ./user-service/.
      dockerfile: Dockerfile
    ports:
    - 8082:8082
    networks:
      - mynet
    command:
      - "--redis.address=redis"
      - "--nacos.address=nacos"
      - "--mysql.address=mysql"
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/.
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    networks:
      - mynet
    command:
      - "--nacos.address=nacos"
networks:
  mynet:
    driver: bridge