jwt:
  secret: rayux
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.address}:8848
  application:
    name: sso
server:
  port: 8083