spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.118.139:8849
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.118.139:3306/ray_user?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 192.168.118.139
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8082